### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Bundy455** [judge2020/AltisLauncher-Mac#2]
I don't know if I'm doing something wrong but when I sign in it says The procedure entry point CloseTouchInputHandle could not be located in the dynamic link library USER32.dll let me know if I'm doing something wrong.

**Comment by judge2020** [comment]
This launcher has been depreciated since it no longer works (because of our new injector protection), We are working on an official mac client.

**Comment by Bundy455** [comment]
ok any ideas when it will release?
